apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
  namespace: default
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/mnt/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-n-1