apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
    version: v2-2-0
  name: jenkins-v2-2-0
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      version: v2-2-0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins
        version: v2-2-0
        environment: dev
    spec:
      containers:
        - image: rfaguiar/jenkins-as-code:2.2.0
          name: jenkins
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KUBERNETES_SERVER_URL
              value: "https://192.168.99.100:8443"
            - name: JENKINS_SERVER_URL
              value: "http://default.jenkins.local"
            - name: PROMETHEUS_NAMESPACE
              value: "istio-system"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10