apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins-master
  name: jenkins-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins-master
        environment: dev
    spec:
      containers:
        - image: rfaguiar/jenkins-as-code:2.5.3
          name: jenkins-master
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: jnlp
              containerPort: 50000
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
            - name: KUBERNETES_SERVER_URL
              value: https://192.168.50.11:6443
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: JENKINS_SERVER_URL
              value: http://jenkins:8080
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10
#          volumeMounts:
#            - name: jenkins-home
#              mountPath: "/var/jenkins_home"
#      volumes:
#        - name: jenkins-home
#          persistentVolumeClaim:
#            claimName: "jenkins-volume-claim"
#            readOnly: false