apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
  namespace: default
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  ports:
    - name: http
      nodePort: 31980
      port: 8080
      targetPort: 8080
    - name: agent
      nodePort: 31500
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins